name: Run quality gates
run-name: ${{ github.actor }} - Antiseptic
on: [push]
jobs:
  quality-check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Python Setup Rye
        uses: eifinger/setup-rye@v3.0.3
      - name: Install Bombsite
        run: rye sync
      - name: Run Ruff linter
        run: rye run ruff check
      - name: Check formatting with Ruff code formatter
        run: rye run ruff format --check
      - name: Run Mypy
        run: rye run mypy python/

  run-rust-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Cargo
        uses: Swatinem/rust-cache@v2
      - name: Run unit-tests
        shell: bash
        run: cargo test
