name: Run quality gates
run-name: ${{ github.actor }} - Antiseptic
on: [push]
jobs:
  quality-check-python:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.8"
      - name: Install Bombsite
        run: uv sync
      - name: Run Ruff linter
        run: uv run ruff check
      - name: Check formatting with Ruff code formatter
        run: uv run ruff format --check
      - name: Run Mypy
        run: uv run mypy python/

  run-rust-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Cargo
        uses: Swatinem/rust-cache@v2
      - name: Run unit-tests
        shell: bash
        run: cargo test
